name: Run tests

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
         postgres_version: ['14','16']
    services:
      postgres:
        image: postgres:${{ matrix.postgres_version }}
        env:
          POSTGRES_DB: reminder_scheduler
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    env:
      DATABASE_URL: postgres://postgres:postgres@localhost/reminder_scheduler
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install dependancies
        run: pip install -r requirements.txt -r requirements-dev.txt
      - name: Run tests
        run: |
          python manage.py makemigrations --check
          pytest
