name: Run tests

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
         postgres_version: ['14','16']
    services:
      postgres:
        image: postgres:${{ matrix.postgres_version }}
        env:
          POSTGRES_DB: reminder_scheduler
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    env:
      RP_SIDEKICK_DATABASE: postgres://postgres:postgres@localhost/reminder_scheduler
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install dependancies
        run: |
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc 2>/dev/null | sudo apt-key add -
          sudo apt-get update
          sudo apt-get -y install postgresql-14
          sudo apt-get -y install postgresql-16
          pip install -r requirements.txt -r requirements-dev.txt
      - name: Run tests
        run: pytest
