name: Run tests

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
         postgres_version: ['14','16']
    services:
      postgres:
        image: postgres:${{ matrix.postgres_version }}
        env:
          POSTGRES_DB: reminder_scheduler
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    env:
      DATABASE_URL: postgres://postgres:postgres@localhost/reminder_scheduler
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.9'
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: "1.8.3"    
      - name: Install dependencies
        id: install-deps
        run: |
          poetry install
      - name: Check formatting
        # Lints/tests should always run, even if other lints/tests have failed.
        if: success() || failure() && steps.install-deps.outcome == 'success'
        run: |
          poetry run ruff format --check 
      - name: Lint
        if: success() || failure() && steps.install-deps.outcome == 'success'
        run: |
          poetry run ruff check 
      - name: Run tests
        if: success() || failure() && steps.install-deps.outcome == 'success'
        run: |
          poetry run pytest -vv
