# Generated by Django 3.1.2 on 2020-10-05 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReminderSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_time', models.DateTimeField(blank=True, null=True)),
                ('recipient_id', models.CharField(max_length=30)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.remindercontent')),
            ],
        ),
        migrations.AddIndex(
            model_name='reminderschedule',
            index=models.Index(condition=models.Q(sent_time__isnull=True), fields=['sent_time', 'schedule_time'], name='sent_time'),
        ),
    ]
