# Generated by Django 3.1.2 on 2020-10-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reminderschedule',
            name='sent_time',
        ),
        migrations.AddField(
            model_name='reminderschedule',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='reminderschedule',
            index=models.Index(condition=models.Q(('cancelled', False), ('sent_time__isnull', True)), fields=['sent_time', 'schedule_time'], name='sent_time'),
        ),
    ]
